name: CONTINUOUS INTEGRATIONS
on:
  push:
    branches-ignore:
      - '!main'
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node.js 10 setup
        with:
          node-version: 10
        uses: actions/setup-node@v2
      - name: installation of dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  integration-local:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node.js 10 setup
        uses: actions/setup-node@v2
        with:
          node-version: 10
      - name: installation of dependencies
        run: npm ci
      - name: start serverest locally
        run: 'docker run -d -p 3000:3000 paulogoncalvesbh/serverest'
      - name: api tests
        run: 'npm run cy:run'
        env:
          CYPRESS_APP_URL: 'http://localhost:3000'
          CYPRESS_EMAIL: '${{ secrets.EMAIL }}'
          CYPRESS_PASSWORD: '${{ secrets.PASSWORD }}'
  allure-report:
    needs:
      - integration-local
    name: generate allure report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: allure report action from marketplace
        uses: ulucasfraga/cypress_api_for_studies@main
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 10
      - name: deploy report to github pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: '${{ secrets.GH_TOKEN }}'
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
