name: CONTINUOUS INTEGRATIONS
on:
  push:
    branches-ignore:
      - '!main'
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node.js 10 setup
        with:
          node-version: 10
        uses: actions/setup-node@v2
      - name: installation of dependencies
        run: npm ci
      - name: lint
        run: npm run lint
  integration-local:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node.js 10 setup
        uses: actions/setup-node@v2
        with:
          node-version: 10
      - name: installation of dependencies
        run: npm ci
      - name: start serverest locally
        run: 'docker run -d -p 3000:3000 paulogoncalvesbh/serverest'
      - name: api tests
        run: 'npm run cy:run'
        env:
          CYPRESS_APP_URL: 'http://localhost:3000'
          CYPRESS_EMAIL: '${{ secrets.EMAIL }}'
          CYPRESS_PASSWORD: '${{ secrets.PASSWORD }}'
  generate-report:
        needs:
        - integration-local
        runs-on: ubuntu-16.04
        steps:
            - uses: actions/checkout@v2
            - name: Download Cypress
              uses: bahmutov/npm-install@v1
              env:
                  CYPRESS_INSTALL_BINARY: 0

            - name: check cypress cache
              run: |
                  npx cypress cache path
                  npx cypress cache list
            - name: restore / cache the binary
              id: cache-cypress
              uses: actions/cache@v1
              with:
                  path: ~/.cache/Cypress
                  key: >-
                      cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package.json')
                      }}
            - name: prepare allure history
              run: |
                  rm -r allure-results/*
                  cp -r ./allure-report/history ./allure-results/history
                  rm -r allure-report/*
            - name: install cypress
              run: |
                  npx cypress install
                  npx cypress cache list
            - name: run cypress
              run: npm run cy:run
            - name: generate allure report
              if: always()
              uses: afiore/action-allure-report@v0.1.0

            - name: commit report results
              if: always()
              run: |
                  git config --local user.email "lucass.fragaa@gmail.com"
                  git config --local user.name "Lucas Fraga"
                  git add allure-report -f
                  git add allure-results -f
                  git commit -m "[chore] autogenerate Allure report" -a
            - name: Push changes
              if: always()
              uses: ad-m/github-push-action@master
              with:
                  CYPRESS_GH_TOKEN: '${{ secrets.GH_TOKEN }}'
                  force: true