name: CONTINUOUS INTEGRATIONS
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: node.js 10 setup
        with:
          node-version: 10
        uses: actions/setup-node@v2
      - name: Installation of dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  integration-tests-and-allure-report:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node.js 10 setup
        uses: actions/setup-node@v2
        with:
          node-version: 10
      - name: Installation of dependencies
        run: npm ci
      - name: Start serveRest locally
        run: docker run -d -p 3000:3000 paulogoncalvesbh/serverest
      - name: Api tests
        run: npm run cy:run
        env:
          CYPRESS_APP_URL: http://localhost:3000
          CYPRESS_EMAIL: ${{ secrets.EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}
      - name: Get allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report
        with:
          allure_results: allure-results
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to github pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
