name: CI
on:
  pull_request: null
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  lint:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [10]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: node.js 10 setup
        with:
          node-version: ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - name: Installation of dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  api-tests-and-report:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [10]
        ci_node_total: [2]
        ci_node_index: [0, 1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node.js 10 setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installation of dependencies
        run: npm ci
      - name: Start serveRest locally
        run: docker run -d -p 3000:3000 paulogoncalvesbh/serverest
      - name: Api tests
        # run: npm run cy:run
        env:
          CYPRESS_APP_URL: http://localhost:3000
          CYPRESS_EMAIL: ${{ secrets.EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.PASSWORD }}
          KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS: ${{ secrets.KNAPSACK_PRO_TEST_SUITE_TOKEN_CYPRESS }}
          KNAPSACK_PRO_CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          KNAPSACK_PRO_CI_NODE_INDEX: ${{ matrix.ci_node_index }}
          KNAPSACK_PRO_FIXED_QUEUE_SPLIT: true
        run: |
          $(npm bin)/knapsack-pro-cypress
      - name: Get allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Allure report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
      - name: Deploy report to github pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
